=== CodewarsTools/codewars-api-schemas-tests/schemas/user/profile.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "user-profile",

  "type": "object",

  "required": [
    "id",
    "username",
    "honor",
    "ranks",
    "codeChallenges",
    "leaderboardPosition"
  ],

  "properties": {
    "id": {
      "type": "string"
    },

    "username": {
      "type": "string"
    },

    "name": {
      "type": "string"
    },

    "honor": {
      "type": "integer",
      "minimum": 0
    },

    "clan": {
      "type": "string"
    },

    "leaderboardPosition": {
      "type": "integer",
      "minimum": 1
    },

    "skills": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },

    "ranks": {
      "type": "object",

      "required": [
        "overall",
        "languages"
      ],

      "properties": {
        "overall": {
          "type": "object",

          "required": [
            "rank",
            "name",
            "color",
            "score"
          ],

          "properties": {
            "rank": {
              "type": "integer",
              "minimum": -8,
              "maximum": 8
            },

            "name": {
              "type": "string",
              "enum": [
                "8 kyu",
                "7 kyu",
                "6 kyu",
                "5 kyu",
                "4 kyu",
                "3 kyu",
                "2 kyu",
                "1 kyu",
                "1 dan",
                "2 dan",
                "3 dan",
                "4 dan",
                "5 dan",
                "6 dan",
                "7 dan",
                "8 dan"
              ]
            },

            "color": {
              "type": "string"
            },

            "score": {
              "type": "integer",
              "minimum": 0
            }
          }
        },

        "languages": {
          "type": "object",

          "additionalProperties": {
            "type": "object",

            "required": [
              "rank",
              "name",
              "color",
              "score"
            ],

            "properties": {
              "rank": {
                "type": "integer",
                "minimum": -8,
                "maximum": 8
              },

              "name": {
                "type": "string",
                "enum": [
                  "8 kyu",
                  "7 kyu",
                  "6 kyu",
                  "5 kyu",
                  "4 kyu",
                  "3 kyu",
                  "2 kyu",
                  "1 kyu",
                  "1 dan",
                  "2 dan",
                  "3 dan",
                  "4 dan",
                  "5 dan",
                  "6 dan",
                  "7 dan",
                  "8 dan"
                ]
              },

              "color": {
                "type": "string"
              },

              "score": {
                "type": "integer",
                "minimum": 0
              }
            }
          }
        }
      }
    },

    "codeChallenges": {
      "type": "object",

      "required": [
        "totalAuthored",
        "totalCompleted"
      ],

      "properties": {
        "totalAuthored": {
          "type": "integer",
          "minimum": 0
        },

        "totalCompleted": {
          "type": "integer",
          "minimum": 0
        }
      }
    }
  }
}

=== CodewarsTools/codewars-api-schemas-tests/data/user-profile.json
{
  "id": "625dae5f8f66eb001c7ef330",
  "username": "Krillan",
  "name": "",
  "honor": 29714,
  "clan": "",
  "leaderboardPosition": 184,
  "skills": [],
  "ranks": {
    "overall": {
      "rank": 1,
      "name": "1 dan",
      "color": "black",
      "score": 38060
    },
    "languages": {
      "ruby": {
        "rank": -1,
        "name": "1 kyu",
        "color": "purple",
        "score": 28600
      },
      "sql": {
        "rank": -3,
        "name": "3 kyu",
        "color": "blue",
        "score": 3015
      },
      "javascript": {
        "rank": -2,
        "name": "2 kyu",
        "color": "purple",
        "score": 6801
      },
      "shell": {
        "rank": -5,
        "name": "5 kyu",
        "color": "yellow",
        "score": 416
      }
    }
  },
  "codeChallenges": {
    "totalAuthored": 2,
    "totalCompleted": 4377
  }
}
